In [2]:
import numpy as np
import matplotlib as mp

'''
    행렬 계산을 위한 numpy
    여러 연산을 지원한다.
'''

a = np.array([1,2,3,4])
b = np.array([5,6,7,8]) # 행렬 (배열) 만드는 법.



In [6]:
a + b

array([ 6,  8, 10, 12])

In [10]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.array(range(0,5))

array([0, 1, 2, 3, 4])

In [17]:
print(a.size) # 행렬 안에 들어있는 원소의 개수를 알려준다. len() 과는 다르다.

4


In [26]:
arangeA = np.arange(12) # arange() 함수를 사용하여 range() 함수를 사용하지 않아도 순서대로의 행렬을 만들 수 있다.
print(arangeA)
print("행렬의 길이", len(arangeA))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
행렬의 길이 12


In [27]:
arangeB = arangeA.reshape(2,3,2) # 2행 3열로 바꾸기
print(arangeB) # 나는 왜 ,(콤마) 표시를 안해주지?

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [33]:
print(arangeA.size,' ',arangeB.size)
print(len(arangeA), ' ', len(arangeB)) # size 와 len의 차이를 알 수 있는 대목이다.

12   12
12   2


In [41]:
newShape = np.reshape(arangeB, newshape=(6,2), order='C') # 흐음 오더를 'C' 에서 'F'로 바꾸면 1과 6이 만난다. 포트란이라고 부름
newShape

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
a = np.arange(6)
a = a+1
np.shape(a)

(6,)

In [47]:
# column vector 처럼 만들기
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [51]:
print(np.shape(a)) # 그냥 6열 
print(np.shape(a2)) # 1행 6열
a2 # row vector 이기도 하다.

(6,)
(1, 6)


In [56]:
a3 = a[:, np.newaxis] # row vector 를 column vector 로 바꾼다.
print(a3)
print(a3.shape) # 2차원이다. 1차원은 (6,) 이런식으로 표현된다.

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [61]:
a4 = np.expand_dims(a, axis=1) # axis 는 0 또는 1인데 1이면 행이 늘어나고 0이면 열이 늘어난다.
a4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [62]:
data = np.array([1,2,3])

In [64]:
# 데이터 슬라이싱도 가능하다. np.array 데이터형은
data[0:2]

array([1, 2])

In [65]:
data[1]

2

In [66]:
data[1:]

array([2, 3])

In [67]:
data[1:2]

array([2])

In [68]:
data[:2]

array([1, 2])

In [75]:
data = np.concatenate((data, np.array([123,12,55,1,67])), axis = 0)

In [83]:
# 조건을 사용하여 필요한 부분만 슬라이싱
data[data > 15] 

array([123,  55,  67])

In [84]:
data[data % 3 == 0]

array([  3, 123,  12])

In [85]:
data % 3 == 0 # true false 값으로 반환해준다.

array([False, False,  True,  True,  True, False, False, False])

In [92]:
a5 = np.arange(12)
a5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
a6 = a5.reshape(2,6)
a6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [103]:
a7 = np.hsplit(a6, 3)

In [113]:
b1, b2, b3 = a7
test = np.concatenate((b1,b2,b3), axis=1)

a8 = np.hstack((b2,b1,b3))
a8

array([[ 2,  3,  0,  1,  4,  5],
       [ 8,  9,  6,  7, 10, 11]])

In [127]:
import pandas as pd

f1 = pd.DataFrame(a8)
f1

0  1  2  3   4   5
0  2  3  0  1   4   5
1  8  9  6  7  10  11

In [128]:
f1 + 8

0   1   2   3   4   5
0  10  11   8   9  12  13
1  16  17  14  15  18  19

In [134]:
a8 * 2 % 2 / 3 # // 은 정수 나누기 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [142]:
a8.sum() # np.array 데이터형은 sum() 을 함수처럼 부른다.
f1.sum() # pandas 의 DataFrame 데이터형은 각각의 열들을 더해서 보여준다.

0    10
1    12
2     6
3     8
4    14
5    16
dtype: int64

In [158]:
f1.apply(lambda x: x-8) # DataFrame 데이터프레임은 람다 함수를 사용할 수 있따
#(lambda x : x-5 , a8)

0  1  2  3  4  5
0 -6 -5 -8 -7 -4 -3
1  0  1 -2 -1  2  3

In [161]:
a8.mean() # sum(), mean(), var() -> 분산

5.5

In [170]:
# 랜덤 넘버 array 만들기

rng = np.random

rng = rng.default_rng(0)

AttributeError: module 'numpy.random' has no attribute 'default_rng'

In [171]:
a = np.array(range(1,7))
a

array([1, 2, 3, 4, 5, 6])

In [172]:
np.save('a', a) # array 저장

In [173]:
b = np.load('a.npy') # 저장된 array 로드

In [175]:
b

array([1, 2, 3, 4, 5, 6])

In [176]:
C = np.arange(9)

C = C.reshape(3,3)

In [177]:
np.savetxt('c.csv', C)